In [1]:

import sys
from pathlib import Path
import pandas as pd

In [2]:
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "phase_01":
    PROJECT_ROOT = PROJECT_ROOT.parent.parent

sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

d:\VS Code\DataPilot

In [3]:

from src.cleaning.data_cleaner import prepare_dataset

from src.analysis.sales_analysis import (
    total_sales,
    sales_by_region,
    sales_by_category,
    yearly_growth,
    region_summary,
    top_products
)

from src.analysis.shipping_analysis import (
    shipping_by_mode,
    shipping_range
)

In [4]:

from src.cleaning.data_cleaner import prepare_dataset

from src.analysis.sales_analysis import (
    total_sales,
    sales_by_region,
    sales_by_category,
    yearly_growth,
    region_summary,
    top_products
)

from src.analysis.shipping_analysis import (
    shipping_by_mode,
    shipping_range
)

In [21]:
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "superstore.csv"

df = pd.read_csv(DATA_PATH)

df = prepare_dataset(df)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Order Year,Order Month,Order Month Name,Order Quarter,Order Day,Shipping Days
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2017,11,November,4,8,3
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017,11,November,4,8,3
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017,6,June,2,12,4
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016,10,October,4,11,7
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2016,10,October,4,11,7

In [6]:
print(f"Total Sales: ${total_sales(df):,.2f}")

Total Sales: $2,261,536.78

In [7]:
sales_by_region(df)

Region
West       710219.6845
East       669518.7260
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

In [8]:
sales_by_category(df)

Category
Technology         827455.8730
Furniture          728658.5757
Office Supplies    705422.3340
Name: Sales, dtype: float64

In [9]:
yearly_growth(df)

                  Sales   Growth %
Order Year
2015        479856.2081        NaN
2016        459436.0054  -4.255484
2017        600192.5500  30.636812
2018        722052.0192  20.303396

In [22]:
region_summary(df)

               Sales  Share %
Region
West     710219.6845    31.40
East     669518.7260    29.60
Central  492646.9132    21.78
South    389151.4590    17.21

In [11]:
top_products(df, 10)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [12]:
top_products(df, 10)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [13]:
shipping_by_mode(df)

Ship Mode
Same Day          0.044610
First Class       2.179214
Second Class      3.249211
Standard Class    5.008363
Name: Shipping Days, dtype: float64

In [14]:
shipping_range(df)

{'minimum_days': np.int64(0),
 'maximum_days': np.int64(7),
 'negative_records': 0}

In [23]:
from src.analysis.data_profiler import (
    profile_dataset,
    numeric_summary,
    missing_value_summary
    
)

In [16]:
profile = profile_dataset(df)

profile

{'rows': 9800,
 'columns': 24,
 'column_names': ['Row ID',
  'Order ID',
  'Order Date',
  'Ship Date',
  'Ship Mode',
  'Customer ID',
  'Customer Name',
  'Segment',
  'Country',
  'City',
  'State',
  'Postal Code',
  'Region',
  'Product ID',
  'Category',
  'Sub-Category',
  'Product Name',
  'Sales',
  'Order Year',
  'Order Month',
  'Order Month Name',
  'Order Quarter',
  'Order Day',
  'Shipping Days'],
 'duplicate_rows': 0,
 'missing_values': {'Row ID': 0,
  'Order ID': 0,
  'Order Date': 0,
  'Ship Date': 0,
  'Ship Mode': 0,
  'Customer ID': 0,
  'Customer Name': 0,
  'Segment': 0,
  'Country': 0,
  'City': 0,
  'State': 0,
  'Postal Code': 11,
  'Region': 0,
  'Product ID': 0,
  'Category': 0,
  'Sub-Category': 0,
  'Product Name': 0,
  'Sales': 0,
  'Order Year': 0,
  'Order Month': 0,
  'Order Month Name': 0,
  'Order Quarter': 0,
  'Order Day': 0,
  'Shipping Days': 0},
 'data_types': {'Row ID': 'int64',
  'Order ID': 'str',
  'Order Date': 'datetime64[us]',
  'Ship Date': 'datetime64[us]',
  'Ship Mode': 'str',
  'Customer ID': 'str',
  'Customer Name': 'str',
  'Segment': 'str',
  'Country': 'str',
  'City': 'str',
  'State': 'str',
  'Postal Code': 'Int64',
  'Region': 'str',
  'Product ID': 'str',
  'Category': 'str',
  'Sub-Category': 'str',
  'Product Name': 'str',
  'Sales': 'float64',
  'Order Year': 'int32',
  'Order Month': 'int32',
  'Order Month Name': 'str',
  'Order Quarter': 'int32',
  'Order Day': 'int32',
  'Shipping Days': 'int64'},
 'numeric_columns': ['Row ID',
  'Postal Code',
  'Sales',
  'Order Year',
  'Order Month',
  'Order Quarter',
  'Order Day',
  'Shipping Days'],
 'categorical_columns': ['Order ID',
  'Ship Mode',
  'Customer ID',
  'Customer Name',
  'Segment',
  'Country',
  'City',
  'State',
  'Region',
  'Product ID',
  'Category',
  'Sub-Category',
  'Product Name',
  'Order Month Name'],
 'datetime_columns': ['Order Date', 'Ship Date']}

In [24]:
numeric_summary(df)

,Row ID,Order Date,Ship Date,Postal Code,Sales,Order Year,Order Month,Order Quarter,Order Day,Shipping Days
count,9800.000000,9800,9800,9789.0,9800.000000,9800.000000,9800.000000,9800.000000,9800.000000,9800.000000
mean,4900.500000,2017-05-01 05:13:51.673469,2017-05-05 04:17:52.653061,55273.322403,230.769059,2016.724184,7.818469,2.885816,15.486837,3.961122
min,1.000000,2015-01-03 00:00:00,2015-01-07 00:00:00,1040.0,0.444000,2015.000000,1.000000,1.000000,1.000000,0.000000
25%,2450.750000,2016-05-24 00:00:00,2016-05-27 18:00:00,23223.0,17.248000,2016.000000,5.000000,2.000000,8.000000,3.000000
50%,4900.500000,2017-06-26 00:00:00,2017-06-29 00:00:00,58103.0,54.490000,2017.000000,9.000000,3.000000,16.000000,4.000000
75%,7350.250000,2018-05-15 00:00:00,2018-05-19 00:00:00,90008.0,210.605000,2018.000000,11.000000,4.000000,23.000000,5.000000
max,9800.000000,2018-12-30 00:00:00,2019-01-05 00:00:00,99301.0,22638.480000,2018.000000,12.000000,4.000000,31.000000,7.000000
std,2829.160653,NaN,NaN,32041.223413,626.651875,1.123984,3.281905,1.057449,8.753733,1.749614

In [18]:
missing_value_summary(df)

             Missing Count  Missing %
Postal Code             11       0.11

In [19]:
from src.analysis.data_profiler import dataset_overview

In [20]:
dataset_overview(df)

==================================================
DATASET OVERVIEW
==================================================
Rows: 9800
Columns: 24
Duplicate Rows: 0

Numeric Columns:
 - Row ID
 - Postal Code
 - Sales
 - Order Year
 - Order Month
 - Order Quarter
 - Order Day
 - Shipping Days

Categorical Columns:
 - Order ID
 - Ship Mode
 - Customer ID
 - Customer Name
 - Segment
 - Country
 - City
 - State
 - Region
 - Product ID
 - Category
 - Sub-Category
 - Product Name
 - Order Month Name

Datetime Columns:
 - Order Date
 - Ship Date

Missing Values:
 - Postal Code: 11